### ISSUE TITLE
Crash at Siege, e1.4.1

### ISSUE THREAD

**Issue by Yilmas** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#396]
![image](https://user-images.githubusercontent.com/6323003/85312054-99774700-b4b6-11ea-944a-bc14cda8e13c.png)

The CTD occured when I attempted to join an ongoing siege, after I clicked "Attack".
Not sure if this is related to #335

**Comment by JoeFwd** [comment]
If you still have a save that leads to this crash, can you check if this build [CommunityPatch_e1.4.1_siege_crash_fix.zip](https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/files/4815402/CommunityPatch_e1.4.1_siege_crash_fix.zip)
 solves this issue ?

**Comment by Yilmas** [comment]
> If you still have a save that leads to this crash, can you check if this build [CommunityPatch_e1.4.1_siege_crash_fix.zip](https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/files/4815402/CommunityPatch_e1.4.1_siege_crash_fix.zip)
> solves this issue ?

Issue is fixed.

**Comment by khaled-f5** [comment]
> If you still have a save that leads to this crash, can you check if this build [CommunityPatch_e1.4.1_siege_crash_fix.zip](https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/files/4815402/CommunityPatch_e1.4.1_siege_crash_fix.zip)
> solves this issue ?

I've tried this build and I still get a crash when trying to enter a city.
